window.defaults = {
	toolId: 0,
	materialId: 0,
	diameter: 100,
};

window.dataIn = [
	{
		id: 0,
		name: "Точение",
		materials: [
			{
				id: 0,
				name: "Сталь",
				turnoverClean: 350,
				turnoverBlack: 200,
				supplyClean: "0.05-0.1",
				supply: "0.15-0.4",
				removalClean: "0.1-0.3",
				removal: "1-4",
			},
			{
				id: 1,
				name: "Нержавеющая сталь",
				turnoverClean: 150,
				turnoverBlack: 250,
				supplyClean: "0.05-0.1",
				supply: "0.15-0.2",
				removalClean: "0.1-0.3",
				removal: "1-4",
			},
			{
				id: 2,
				name: "Чугун",
				turnoverClean: 1200,
				turnoverBlack: 250,
				supplyClean: "0.1-0.2",
				supply: "0.2-0.4",
				removalClean: "0.1-0.3",
				removal: "1-4",
			},
			{
				id: 3,
				name: "Алюминий",
				turnoverClean: 2000,
				turnoverBlack: 500,
				supplyClean: "0.05-0.1",
				supply: "0.3-0.8",
				removalClean: "0.1-0.3",
				removal: "4-8",
			},
			{
				id: 4,
				name: "Жаропрочные сплавы",
				turnoverClean: 200,
				turnoverBlack: 70,
				supplyClean: "0.1-0.2",
				supply: "0.2-0.4",
				removalClean: "0.3-0.5",
				removal: "0.8-1.5",
			},
			{
				id: 5,
				name: "Сплавы высокой твёрдости",
				turnoverClean: 250,
				turnoverBlack: 120,
				supplyClean: "0.05-0.15",
				supply: "0.2-0.4",
				removalClean: "0.3-0.5",
				removal: "0.8-1.5",
			},
		]
	},
	{
		id: 1,
		name: "Канавка",
		materials: [
			{
				id: 0,
				name: "Сталь",
				turnoverClean: 230,
				turnoverBlack: 130,
				supplyClean: "0.05-0.1",
				supply: "0.2-0.3",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 1,
				name: "Нержавеющая сталь",
				turnoverClean: 220,
				turnoverBlack: 100,
				supplyClean: "0.05-0.1",
				supply: "0.2-0.3",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 2,
				name: "Чугун",
				turnoverClean: 250,
				turnoverBlack: 90,
				supplyClean: "0.05-0.1",
				supply: "0.2-0.3",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 3,
				name: "Алюминий",
				turnoverClean: 1500,
				turnoverBlack: 500,
				supplyClean: "0.05-0.1",
				supply: "0.3-0.4",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 4,
				name: "Жаропрочные сплавы",
				turnoverClean: 90,
				turnoverBlack: 50,
				supplyClean: "0.05-0.1",
				supply: "0.1-0.15",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 5,
				name: "Сплавы высокой твёрдости",
				turnoverClean: 120,
				turnoverBlack: 100,
				supplyClean: "0.05-0.1",
				supply: "0.1-0.15",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
		]
	},
	{
		id: 2,
		name: "Резьба",
		materials: [
			{
				id: 0,
				name: "Сталь",
				turnoverClean: 120,
				turnoverBlack: 0,
				supplyClean: "Шаг резьбы",
				// supply: "Шаг резьбы",
				removalClean: "0.1-0.2",
				// removal: "1-4",
			},
			{
				id: 1,
				name: "Нержавеющая сталь",
				turnoverClean: 140,
				turnoverBlack: 0,
				supplyClean: "Шаг резьбы",
				// supply: "Шаг резьбы",
				removalClean: "0.1-0.2",
				// removal: "1-4",
			},
			{
				id: 2,
				name: "Чугун",
				turnoverClean: 145,
				turnoverBlack: 0,
				supplyClean: "Шаг резьбы",
				// supply: "Шаг резьбы",
				removalClean: "0.1-0.2",
				// removal: "1-4",
			},
			{
				id: 3,
				name: "Алюминий",
				turnoverClean: 450,
				turnoverBlack: 0,
				supplyClean: "Шаг резьбы",
				// supply: "Шаг резьбы",
				removalClean: "0.1-0.2",
				// removal: "1-4",
			},
			{
				id: 4,
				name: "Жаропрочные сплавы",
				turnoverClean: 25,
				turnoverBlack: 0,
				supplyClean: "Шаг резьбы",
				// supply: "Шаг резьбы",
				removalClean: "0.1-0.2",
				// removal: "1-4",
			},
			{
				id: 5,
				name: "Сплавы высокой твёрдости",
				turnoverClean: 30,
				turnoverBlack: 0,
				supplyClean: "Шаг резьбы",
				// supply: "Шаг резьбы",
				removalClean: "0.1-0.2",
				// removal: "1-4",
			},
		]
	},
	{
		id: 3,
		name: "Сверление",
		materials: [
			{
				id: 0,
				name: "Сталь",
				turnoverClean: 120,
				turnoverBlack: 70,
				supplyClean: "0.03-0.06",
				supply: "0.1-0.2",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 1,
				name: "Нержавеющая сталь",
				turnoverClean: 70,
				turnoverBlack: 40,
				supplyClean: "0.03-0.06",
				supply: "0.1-0.15",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 2,
				name: "Чугун",
				turnoverClean: 150,
				turnoverBlack: 80,
				supplyClean: "0.05-0.1",
				supply: "0.15-0.25",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 3,
				name: "Алюминий",
				turnoverClean: 320,
				turnoverBlack: 120,
				supplyClean: "0.06-0.1",
				supply: "0.2-0.4",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 4,
				name: "Жаропрочные сплавы",
				turnoverClean: 30,
				turnoverBlack: 10,
				supplyClean: "0.03-0.06",
				supply: "0.06-0.12",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 5,
				name: "Сплавы высокой твёрдости",
				turnoverClean: 25,
				turnoverBlack: 15,
				supplyClean: "0.03-0.06",
				supply: "0.06-0.15",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
		]
	},
	{
		id: 4,
		name: "Метчик",
		materials: [
			{
				id: 0,
				name: "Сталь",
				turnoverClean: 17,
				turnoverBlack: 12,
				supplyClean: "Шаг резьбы",
				supply: "Шаг резьбы",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 1,
				name: "Нержавеющая сталь",
				turnoverClean: 13,
				turnoverBlack: 7,
				supplyClean: "Шаг резьбы",
				supply: "Шаг резьбы",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 2,
				name: "Чугун",
				turnoverClean: 18,
				turnoverBlack: 8,
				supplyClean: "Шаг резьбы",
				supply: "Шаг резьбы",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 3,
				name: "Алюминий",
				turnoverClean: 40,
				turnoverBlack: 19,
				supplyClean: "Шаг резьбы",
				supply: "Шаг резьбы",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 4,
				name: "Жаропрочные сплавы",
				turnoverClean: 2,
				turnoverBlack: 1,
				supplyClean: "Шаг резьбы",
				supply: "Шаг резьбы",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
			{
				id: 5,
				name: "Сплавы высокой твёрдости",
				turnoverClean: 0,
				turnoverBlack: 0,
				supplyClean: "Шаг резьбы",
				supply: "Шаг резьбы",
				// removalClean: "0.1-0.3",
				// removal: "1-4",
			},
		]
	},
	{
		id: 5,
		name: "Фреза",
		materials: [
			{
				id: 0,
				name: "Сталь",
				turnoverClean: 300,
				turnoverBlack: 200,
				supplyClean: "0.05-0.1 на зуб",
				supply: "0.2-0.4 на зуб",
				removalClean: "0.4-1",
				removal: "1-3",
			},
			{
				id: 1,
				name: "Нержавеющая сталь",
				turnoverClean: 210,
				turnoverBlack: 150,
				supplyClean: "0.05-0.1 на зуб",
				supply: "0.15-0.3 на зуб",
				removalClean: "0.4-1",
				removal: "1-3",
			},
			{
				id: 2,
				name: "Чугун",
				turnoverClean: 700,
				turnoverBlack: 180,
				supplyClean: "0.05-0.1 на зуб",
				supply: "0.2-0.3 на зуб",
				removalClean: "0.4-1",
				removal: "1-3",
			},
			{
				id: 3,
				name: "Алюминий",
				turnoverClean: 1700,
				turnoverBlack: 800,
				supplyClean: "0.05-0.1 на зуб",
				supply: "0.2-0.4 на зуб",
				removalClean: "0.4-1",
				removal: "1-3",
			},
			{
				id: 4,
				name: "Жаропрочные сплавы",
				turnoverClean: 65,
				turnoverBlack: 30,
				supplyClean: "0.05-0.1 на зуб",
				supply: "0.1-0.2 на зуб",
				removalClean: "0.4-0.7",
				removal: "0.8-1.5",
			},
			{
				id: 5,
				name: "Сплавы высокой твёрдости",
				turnoverClean: 140,
				turnoverBlack: 50,
				supplyClean: "0.05-0.1 на зуб",
				supply: "0.12-0.17 на зуб",
				removalClean: "0.3-0.7",
				removal: "0.8-1.2",
			},
		]
	},
]